# Generated by Django 3.0.6 on 2020-08-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=100, null=True)),
                ('EnterPassword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
