# Generated by Django 3.0.6 on 2020-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0003_auto_20200802_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.CharField(max_length=100, null=True)),
                ('Firstname', models.CharField(max_length=100, null=True)),
                ('Lastname', models.CharField(max_length=100, null=True)),
                ('Phone', models.IntegerField(max_length=10, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='customber',
        ),
        migrations.DeleteModel(
            name='loginform',
        ),
        migrations.DeleteModel(
            name='registrationform',
        ),
    ]
