# Generated by Django 3.0.6 on 2020-08-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0005_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Phone',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
