# Generated by Django 3.0.6 on 2020-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0006_auto_20200814_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Phone',
            field=models.IntegerField(default='9999999999'),
        ),
    ]
