# Generated by Django 3.0.6 on 2020-08-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0008_remove_register_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='EmailId',
        ),
    ]
