# Generated by Django 3.0.6 on 2020-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0009_remove_register_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='EmailId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
