# Generated by Django 3.0.6 on 2020-08-14 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('princesswing', '0010_register_emailid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='reg1',
        ),
    ]
