# Generated by Django 3.0.6 on 2020-09-11 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('princesswing', '0011_auto_20200814_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime(2020, 9, 11, 22, 22, 11, 77443))),
                ('Catagary', models.CharField(max_length=100, null=True)),
                ('Price', models.IntegerField(default='9999999999')),
                ('Qty', models.IntegerField(default='9999999999')),
                ('Image', models.ImageField(upload_to=None)),
                ('Discription', models.CharField(max_length=10000, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
