# Generated by Django 3.0.6 on 2020-09-11 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0012_catagary'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagary',
            name='name',
            field=models.CharField(default='pad', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='catagary',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 0, 48, 12, 132685)),
        ),
        migrations.AlterField(
            model_name='catagary',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
