# Generated by Django 3.0.6 on 2020-09-11 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0013_auto_20200912_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 1, 7, 31, 276524)),
        ),
    ]
