# Generated by Django 3.0.6 on 2020-09-15 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0014_auto_20200912_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 17, 30, 40, 198167)),
        ),
        migrations.AlterField(
            model_name='catagary',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
