# Generated by Django 3.0.6 on 2020-09-15 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0015_auto_20200915_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 17, 34, 59, 602039)),
        ),
        migrations.AlterField(
            model_name='catagary',
            name='Image',
            field=models.ImageField(upload_to='images1/'),
        ),
    ]
