# Generated by Django 3.0.6 on 2020-09-16 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0019_auto_20200915_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 12, 43, 39, 129200)),
        ),
    ]
