# Generated by Django 3.0.6 on 2020-09-30 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0021_auto_20200916_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagary',
            name='id',
        ),
        migrations.AddField(
            model_name='catagary',
            name='cat_ID',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 21, 58, 26, 242245)),
        ),
    ]
