# Generated by Django 3.0.6 on 2020-09-30 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0022_auto_20200930_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 22, 3, 32, 676834)),
        ),
    ]
