# Generated by Django 3.0.6 on 2020-09-30 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0023_auto_20200930_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 22, 4, 35, 253893)),
        ),
    ]
