# Generated by Django 3.0.6 on 2020-10-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0024_auto_20200930_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catagary',
        ),
    ]
