# Generated by Django 3.0.6 on 2020-10-02 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0027_auto_20201002_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 8, 43, 1, 900035)),
        ),
    ]
