# Generated by Django 3.0.6 on 2020-10-05 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0029_auto_20201002_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EnterQTY', models.IntegerField(default='9999999999')),
            ],
        ),
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 12, 48, 8, 69452)),
        ),
    ]
