# Generated by Django 3.0.6 on 2020-10-10 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0031_auto_20201007_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 47, 26, 4230)),
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
