# Generated by Django 3.0.6 on 2020-10-10 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('princesswing', '0032_auto_20201010_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 15, 50, 41, 15733)),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartID', models.AutoField(primary_key=True, serialize=False)),
                ('EnterQTY', models.IntegerField()),
                ('ID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='princesswing.catagary')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
