# Generated by Django 3.0.6 on 2020-10-10 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0033_auto_20201010_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 16, 22, 58, 203401)),
        ),
    ]
