# Generated by Django 3.0.6 on 2020-10-11 05:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('princesswing', '0034_auto_20201010_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='princesswing.catagary'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 11, 5, 17, 590337)),
        ),
    ]
