# Generated by Django 3.0.6 on 2020-10-11 15:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('princesswing', '0035_auto_20201011_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 20, 45, 49, 446900)),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnterQTY', models.IntegerField()),
                ('Email', models.CharField(default='9999999999', max_length=100)),
                ('Address', models.CharField(default='9999999999', max_length=100)),
                ('City', models.CharField(default='9999999999', max_length=100)),
                ('State', models.CharField(default='9999999999', max_length=100)),
                ('FullName', models.CharField(max_length=100)),
                ('ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='princesswing.catagary')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
