# Generated by Django 3.0.6 on 2020-10-11 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princesswing', '0036_auto_20201011_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagary',
            name='Date1',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 20, 46, 57, 979853)),
        ),
    ]
